###
POST https://api.openai.com/v1/completions
Content-Type: application/json
Authorization: Bearer {{OPENAI_API_KEY}}

{
  "model": "text-davinci-003",
  "prompt": "Here is a draft email I just wrote:\n\n\"You are all a bunch of incompetent engineers. There's no way implementing this feature it's going to take a full month; I could do it in one week. I'm sure you can do better if we all stop wasting time role-playing in Scrum meetings.\"\n\nMake it polite\n\n",
  "temperature": 0.7,
  "max_tokens": 256,
  "top_p": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0
}